apiVersion: v1
kind: Service
metadata:
  name: ignite-service
  labels:
    app: ignite
spec:
  type: ClusterIP
  ports:
    - port: 10800
      targetPort: 10800
      name: jdbc
  selector:
    app: ignite