apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"creationTimestamp":"2025-01-13T13:17:32Z","deletionTimestamp":"2025-01-14T06:28:48Z","labels":{"kubernetes.io/metadata.name":"kubedb","pod-security.kubernetes.io/enforce":"restricted"},"name":"kubedb","resourceVersion":"343881","uid":"ba2eddf6-c06f-4b2c-a074-e9f17ca937e9"},"spec":{},"status":{"conditions":[{"lastTransitionTime":"2025-01-14T06:28:58Z","message":"Discovery failed for some groups, 2 failing: unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: stale GroupVersion discovery: mutators.kubedb.com/v1alpha1, validators.kubedb.com/v1alpha1: stale GroupVersion discovery: validators.kubedb.com/v1alpha1","reason":"DiscoveryFailed","status":"True","type":"NamespaceDeletionDiscoveryFailure"},{"lastTransitionTime":"2025-01-14T06:28:53Z","message":"All legacy kube types successfully parsed","reason":"ParsedGroupVersions","status":"False","type":"NamespaceDeletionGroupVersionParsingFailure"},{"lastTransitionTime":"2025-01-14T06:28:53Z","message":"All content successfully deleted, may be waiting on finalization","reason":"ContentDeleted","status":"False","type":"NamespaceDeletionContentFailure"},{"lastTransitionTime":"2025-01-14T06:28:58Z","message":"All content successfully removed","reason":"ContentRemoved","status":"False","type":"NamespaceContentRemaining"},{"lastTransitionTime":"2025-01-14T06:28:53Z","message":"All content-preserving finalizers finished","reason":"ContentHasNoFinalizers","status":"False","type":"NamespaceFinalizersRemaining"}],"phase":"Terminating"}}
  creationTimestamp: "2025-01-13T13:17:32Z"
  deletionTimestamp: "2025-01-14T06:28:48Z"
  labels:
    kubernetes.io/metadata.name: kubedb
    pod-security.kubernetes.io/enforce: restricted
  name: kubedb
  resourceVersion: "343981"
  uid: ba2eddf6-c06f-4b2c-a074-e9f17ca937e9
spec:
  finalizers:
status:
  conditions:
  - lastTransitionTime: "2025-01-14T06:28:58Z"
    message: 'Discovery failed for some groups, 2 failing: unable to retrieve the
      complete list of server APIs: mutators.kubedb.com/v1alpha1: stale GroupVersion
      discovery: mutators.kubedb.com/v1alpha1, validators.kubedb.com/v1alpha1: stale
      GroupVersion discovery: validators.kubedb.com/v1alpha1'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2025-01-14T06:28:53Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2025-01-14T06:28:53Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2025-01-14T06:28:58Z"
    message: All content successfully removed
    reason: ContentRemoved
    status: "False"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2025-01-14T06:28:53Z"
    message: All content-preserving finalizers finished
    reason: ContentHasNoFinalizers
    status: "False"
    type: NamespaceFinalizersRemaining
  phase: Terminating
