{
 "title": "kubedb.com / Memcached / demo / memcached",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Memcached Phase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "KubeDB Memcached Phase Not Ready",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubedb_com_memcached_status_phase{app=\"memcached\",namespace=\"demo\",phase=\"NotReady\"}"
    }
   ]
  },
  {
   "title": "KubeDB Memcached Phase Critical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubedb_com_memcached_status_phase{app=\"memcached\",namespace=\"demo\",phase=\"Critical\"}"
    }
   ]
  },
  { "title": "Memcached Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memcached Down",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min by (service) (memcached_up{job=\"kubedb-databases\",namespace=\"demo\",service=\"memcached-stats\"})"
    }
   ]
  },
  {
   "title": "Memcached Service Respawn",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (service) (memsql_up{job=\"kubedb-databases\",namespace=\"demo\",service=\"memcached-stats\"})"
    }
   ]
  },
  {
   "title": "Memcached Connection Throttled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (service) (max_over_time(memsql_status_threads_connected{job=\"kubedb-databases\",namespace=\"demo\",service=\"memcached-stats\"}[1m]) / memsql_variable_max_connections{job=\"kubedb-databases\",namespace=\"demo\",service=\"memcached-stats\"} * 100)"
    }
   ]
  },
  {
   "title": "Memcached Connections None Minor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (service) (max_over_time(memsql_status_threads_running{job=\"kubedb-databases\",namespace=\"demo\",service=\"memcached-stats\"}[1m]) / memsql_variable_max_connections{job=\"kubedb-databases\",namespace=\"demo\",service=\"memcached-stats\"} * 100)"
    }
   ]
  },
  {
   "title": "Memcached Items None Minor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min by (service) (memsql_status_uptime{job=\"kubedb-databases\",namespace=\"demo\",service=\"memcached-stats\"})"
    }
   ]
  },
  {
   "title": "Memcached Evictions Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (service) (rate(memsql_status_queries{job=\"kubedb-databases\",namespace=\"demo\",service=\"memcached-stats\"}[1m]))"
    }
   ]
  }
 ]
}