apiVersion: v1
kind: Service
metadata:
  name: ignite-metrics
  namespace: ignite
  labels:
    app: ignite
spec:
  selector:
    app: ignite
  ports:
  - name: metrics
    port: 9000
    targetPort: 9000
