apiVersion: ops.kubedb.com/v1alpha1
kind: MemcachedOpsRequest
metadata:
  name: memcached-mc
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: mc1
  verticalScaling:
    memcached:
      resources:
        requests:
          memory: "200Mi"
          cpu: "200m"
        limits:
          memory: "200Mi"
          cpu: "200m"